# Adapted from https://github.com/commercialhaskell/stack
language: c
sudo: false

cache:
    directories:
        - $HOME/.ghc
        - $HOME/.cabal
        - $HOME/.stack
        - .stack-work

matrix:
  include:
    # ghc 7.10.3
  - env: STACK='stack --resolver=lts-6.0' CACHE_NAME=7.10.3
    addons: {apt: {packages: [libgmp-dev]}}
    # ghc 8.0.1
  - env: STACK='stack --resolver=lts-7.4' CACHE_NAME=8.0.1
    addons: {apt: {packages: [libgmp-dev]}}
    # ghc 8.0.2
  - env: STACK='stack --resolver=lts-8.24' CACHE_NAME=8.0.2
    addons: {apt: {packages: [libgmp-dev]}}
    # ghc 8.2.2
  - env: STACK='stack --resolver=lts-10.6' CACHE_NAME=8.2.2
    addons: {apt: {packages: [libgmp-dev]}}
    # Use the resolver in stack.yaml
  - env: STACK=stack CACHE_NAME=stack-linux
    addons: {apt: {packages: [libgmp-dev]}}
  - env: STACK=stack CACHE_NAME=stack-osx
    os: osx
    addons: {apt: {packages: [libgmp-dev]}}


install:
 - unset CC
 - export PATH=$HOME/.local/bin:/opt/ghc/$GHCVER/bin:$PATH
 - ./.travis/install-ghr.sh
 - ./.travis/install-stack.sh

script:
 - echo "$(stack ghc -- --version) [$(stack ghc -- --print-project-git-commit-id 2> /dev/null || echo '?')]"
 - GHC_OPTIONS="-Werror"
 - |
   set -ex
   # Run tests
   $STACK --no-terminal test :gold-tests --ghc-options="$GHC_OPTIONS"
   set +ex

after_success:
 - |
   # Build and ship binary
   ./.travis/attach-binary.sh

