flags: {}
packages:
  - inline
  - known
  - satisfy
  - classes
  - plugin
  - examples
  - graphics
  - hardware
  #- sandbox
extra-deps:
  # Extra packages
  - git: https://github.com/ku-fpg/netlist
    commit: 0f50a9cfd947885cac7fc392a5295cffe0b3ac31
    subdirs:
      - netlist
      - verilog
      - netlist-to-verilog

  # The next three provide instances for GHC.Generics
  - pointed-5.0.1
  - keys-3.12.1
  - adjunctions-4.4
  - z3-4.3.1         # for the SMT category
  - vector-sized-1.1.1.0  # for GHC 8.6
  # - indexed-list-literals-0.1.0.1
  - indexed-list-literals-0.2.1.2
  - ghc-typelits-knownnat-0.6
  - ghc-typelits-natnormalise-0.6.2
  - ghc-tcplugins-extra-0.3
  - newtype-generics-0.5.3
  - language-glsl-0.3.0
  - NumInstances-1.4

# resolver: lts-9.21  # ghc-8.0.2
# resolver: lts-11.22 # ghc-8.2.2
# resolver: lts-12.14 # ghc-8.4.3
# resolver: lts-12.19 # ghc-8.4.4
# resolver: lts-13.0 # ghc-8.6.3
# resolver: lts-13.13 # ghc-8.6.4
# resolver: lts-14.6 # ghc-8.6.5

resolver: nightly-2019-11-20 # ghc-8.8.1

## Work-around for several version incompatibilities with GHC 8.8.1
allow-newer: true
