resolver: lts-9.1

packages:
- classes
- plugin
- examples
- graphics
- hardware
- location:
    git: https://github.com/ku-fpg/netlist
    commit: c58d089f0349e9a3e9f9e264c7108c3d0b4ea4fd
  extra-dep: true
  subdirs:
  - netlist
  - verilog
  - netlist-to-verilog

extra-deps:
# - z3-4.1.0
- hmatrix-0.18.0.0
- language-glsl-0.2.1
- newtype-generics-0.5.0.1
- random-shuffle-0.0.4
- JuicyPixels-3.2.8.2

## We'll need a later NumInstances for GHC 8.2.1, but first must adapt to some
## GHC API changes. See personal notes 2017-08-16.
