flags: {}
packages:
- inline
- satisfy
- classes
- plugin
- examples
- graphics
- hardware
- sandbox
- location:
    git: https://github.com/ku-fpg/netlist
    commit: c58d089f0349e9a3e9f9e264c7108c3d0b4ea4fd
  subdirs:
  - netlist
  - verilog
  - netlist-to-verilog
  extra-dep: true
extra-deps:
  # The next three provide instances for GHC.Generics
  - pointed-5.0.1
  - keys-3.12
  - adjunctions-4.4
  - z3-4.3.1         ## For the SMT category
  - vector-sized-1.0.0.0
  - indexed-list-literals-0.1.0.1
  # The next three are for ConCat.Finite
  - ghc-typelits-knownnat-0.5
  - ghc-typelits-natnormalise-0.6.1
  - ghc-tcplugins-extra-0.3

resolver: lts-9.20
