flags: {}
packages:
- inline
- known
- satisfy
- classes
- plugin
- examples
- graphics
- hardware
- sandbox
- location:
    git: https://github.com/ku-fpg/netlist
    commit: 0f50a9cfd947885cac7fc392a5295cffe0b3ac31
  subdirs:
  - netlist
  - verilog
  - netlist-to-verilog
  extra-dep: true
extra-deps:
  # The next three provide instances for GHC.Generics
  - pointed-5.0.1
  - keys-3.12.1
  - adjunctions-4.4

  # Needed for containers-0.6.0.1 (which I don't really need)
  - Cabal-2.4.0.1
  - free-5.1
  - semigroupoids-5.3.1
  - base-orphans-0.8

  - containers-0.6.0.1
  # - containers-0.5.11.0
  - z3-4.3.1         # for the SMT category
  - vector-sized-1.1.1.0  # for GHC 8.6
  # - indexed-list-literals-0.1.0.1
  - indexed-list-literals-0.2.1.2
  - ghc-typelits-knownnat-0.6
  - ghc-typelits-natnormalise-0.6.2
  - ghc-tcplugins-extra-0.3
  - newtype-generics-0.5.3
  - language-glsl-0.3.0
  - NumInstances-1.4

# resolver: lts-9.21  # ghc-8.0.2
# resolver: lts-11.22 # ghc-8.2.2
# resolver: lts-12.14 # ghc-8.4.3
# resolver: lts-12.19 # ghc-8.4.4

resolver: lts-13.0 # ghc-8.6.3
