flags: {}
packages:
- inline
- known
- satisfy
- classes
- plugin
- examples
- graphics
- hardware
- sandbox
- location:
    git: https://github.com/ku-fpg/netlist
    commit: 0f50a9cfd947885cac7fc392a5295cffe0b3ac31
  subdirs:
  - netlist
  - verilog
  - netlist-to-verilog
  extra-dep: true
- location: # Until vector-sized-1.0.4.1 is on Hackage
    git: https://github.com/expipiplus1/vector-sized
    commit: f80e3ce774d255ee4ba25fcb12a81a76f600e0b0
  extra-dep: true
extra-deps:
  # The next three provide instances for GHC.Generics
  - pointed-5.0.1
  - keys-3.12
  - adjunctions-4.4
  - z3-4.3.1         ## For the SMT category
  # - vector-sized-1.0.4.1  # For GHC 8.6. See above.
  # - indexed-list-literals-0.1.0.1
  - indexed-list-literals-0.2.1.1 # Needed by vector-sized-1.0.4.1
  - ghc-typelits-knownnat-0.5
  - ghc-typelits-natnormalise-0.6.1
  - ghc-tcplugins-extra-0.3
  - newtype-generics-0.5.3
  - language-glsl-0.3.0

# resolver: lts-9.20 # ghc-8.0.2
resolver: lts-11.12 # ghc-8.2.2
# resolver: lts-12.4 # ghc-8.4.3

