flags: {}
packages:
- inline
- classes
- plugin
- examples
- graphics
- hardware
- location:
    git: https://github.com/ku-fpg/netlist
    commit: c58d089f0349e9a3e9f9e264c7108c3d0b4ea4fd
  subdirs:
  - netlist
  - verilog
  - netlist-to-verilog
  extra-dep: true
extra-deps: []
resolver: lts-9.20
